# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barlow Tucker
email: barlowtucker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to write my thoughts on iOS, Swift, Business and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://barlowtucker.github.io" # the base hostname & protocol for your site
twitter_username: barlow_tucker
github_username:  barlowtucker

# Build settings
markdown: kramdown
