# Site setings
name: "Barlow Tucker"
description: "Entrepreneur, Tech Leader, Software Engineer"
meta_description: "Articles on leadership and technology"
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: "me-oct2022-500.jpg"
  greetings: "Start-ups, Leadership, and Technology"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://barlowtucker.com/
#disqus: ""
#mailchimp_url: ""
# Add your GA Tracking Id
ga_analytics: "G-YKE2M3WZSE"

# Contact form setings
#email: barlow@thetuckerbros.com
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: "barlow_tucker"
#facebook: "username"
github: "BarlowTucker"
#codepen: "username"
#dribbble: "username"
medium: "@barlowtucker"
instagram: "barlow_tucker"
#pinterest: "barlowtucker"
linkedin: "barlowtucker"
#producthunt: "@username"
#quora: "username"

# Navigation
navigation:
  - text: Home
    url: /
  - text: About Me
    url: /about
  - text: Coaching
    url: /coaching
  - text: Leadership
    url: /leadership
  # - text: Videos
  #   url: /videos
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
